### ISSUE TITLE
sudo alias causes shutdown command to fail

### ISSUE THREAD

**Issue by sosswald** [chili-epfl/ros4nao#2]
The `bootstrap.sh` script adds the following alias to `.bash_profile`:
```bash
alias sudo='sudo env PATH=$PATH '
```
This alias causes the robot to fail to shut down when the power button is pressed for three seconds. The power button calls `sudo /sbin/shutdown -h now`. According to `/etc/sudoers`, the user `nao` may run this command without a password. But if the alias is present, it gets expanded to `sudo env PATH=... /sbin/shutdown -h now`, so sudo asks for a password that the power button script cannot provide. So it might be better to modify the PATH variable also for root, or to symlink the robotpkg binaries to a directory that is already on the $PATH.

**Comment by severin-lemaignan** [comment]
The issue has been fixed a while ago. Closing it.
